### ISSUE TITLE
django.template.exceptions.TemplateSyntaxError: 'bootstrap' is not a registered tag library.

### ISSUE THREAD

**Issue by bashu** [wooyek/django-opt-out#4]
* Django Opt-out application version: latest
* Django version: 1.11.x
* Python version: 3.5.x
* Operating System: macOS

### Description

 Missing 'bootstrap' template tag library..

### What I Did

Just follow installation instruction and try to load first opt-out view

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/template/response.py", line 82, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/template/response.py", line 64, in resolve_template
    return select_template(template, using=self.using)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/template/loader.py", line 48, in select_template
    return engine.get_template(template_name)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/template/engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/template/engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/template/loaders/cached.py", line 60, in get_template
    template_name, template_dirs, skip,
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/template/loader_tags.py", line 312, in do_extends
    nodelist = parser.parse()
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/template/base.py", line 515, in parse
    raise self.error(token, e)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/template/base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/template/defaulttags.py", line 1095, in load
    lib = find_library(parser, name)
  File "/home/vagrant/.virtualenv/lib/python3.5/site-packages/django/template/defaulttags.py", line 1042, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'bootstrap' is not a registered tag library. Must be one of:
...
```

**Comment by bashu** [comment]
@wooyek or update installation instruction
